### ISSUE TITLE
Pin the base ubuntu version

### ISSUE THREAD

**Issue by crouchr** [optoisolated/MXWeather#6]
Can you please update the Dockerfile to pin the version of Ubuntu used as the base Docker image to the exact version you are using - I tried to build the image Today and I needed to replace python-virtualenv with python3-virtualenv so I'm guessing something has changed in the version of Ubuntu you used versus what is being pulled down now - hence the need for pinning.

Likewise - I'm getting the following error :
 ---> Running in cf0e00d8e878
--2021-01-28 21:00:09--  https://github.com/cumulusmx/CumulusMX/releases/download/b3101/CumulusMXDist3101.zip
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-01-28 21:00:09 ERROR 404: Not Found.

**Comment by optoisolated** [comment]
Ahh yes, good call; I noticed that too.. I'll take a look shortly.

**Comment by crouchr** [comment]
Its cool - I just got the image to build using cumulus 3.4.6 which I think is what your article in https://www.opsbros.com/docker-and-cumulusmx/ showed.
I also had to comment out the line in the Dockerfile where it was copying ./index.htm to /opt/CumulusMX/ as that gave an error - it doesn't seem to have caused an issue not copying this file. I don't have a weather station yet to connect to the container but getting a container running CumulusMX was a pre-requisite for buying a USB weather station so thank you for the great article you wrote - you saved me months of work - thank you.

**Comment by optoisolated** [comment]
No worries :) Happy to see someone got some use out of it. I've dug into the Dockerfile and found that the error with downloading CumulusMX is due to them not uploading the latest version with the same file format they've preveiously used. (Added an 'a' after the build numer). I'll have to redesign the sed to accomodate that; not a biggy but still a bit of a pain. I'll also be updating it to use python3 instead of legacy python which should resolve that issue as well. I'd like to keep the latest ubuntu in use if at all possible.

**Comment by optoisolated** [comment]
Dockerfile is now updated to use Python3 which is a requirement for new builds of Cumulus, and also made a few other fixes including simplifying the Cumulus download from Github (now handles when the build number doesnt match the file name).
